### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by flut1** [mediamonks/seng-event#15]
We want to create a new release with stronger type constructs. See #12 . Here is the status: 

- [x] Create release/2.0.0 branch
- [x] Merge master into new branch and resolve conflicts
- [x] Update babel to stable
- [x] Remove/replace deprecated babel config
- [x] Upgrade TypeScript to latest
- [x] Resolve compiler errors resulting from TS upgrade

Then I think we should go ahead and release 2.0.0-alpha.1 so we can try it out. I think the easiest is to just bypass Travis for publishing this one, because some of the source files don't reach our code coverage threshold yet. After this:

- [x] Some of the constructs in the new typings are somewhat unnecessarily convoluted now that we have a new TS version that supports things like mapped tuple types. We should review these typings so they make more sense (for example, `IsomorphicBaseEvent`)
- [x] Update tests to meet code coverage, possibly adding new tests. As most of the changes are in typings and not in runtime behavior, this shouldn't be too much work
- [x] Update documentation
- [x] PR + release stable

**Comment by flut1** [comment]
@ThaNarie   Can you do a quick review of https://github.com/mediamonks/seng-event/commit/87fa9bc79a6faac0dbd9fa348b6449955dc52537  ?

**Comment by ThaNarie** [comment]
LGTM
